apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-healthcheck
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-healthcheck
  template:
    metadata:
      labels:
        app: nginx-healthcheck
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10


_______________________________________________________
apiVersion: v1
kind: Pod
metadata:
  name: nginx-healthcheck
  namespace: test
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10

      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10